# netlify.toml
[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = """
  default-src 'self';
  script-src 'self' https://js.stripe.com;
  connect-src 'self' https://api.stripe.com;
  frame-src https://js.stripe.com https://hooks.stripe.com;
  img-src 'self' data: https:;
  style-src 'self' 'unsafe-inline';
  base-uri 'self';
  form-action 'self';
  upgrade-insecure-requests;
  """
